slackpro/app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import UserTable
from flask import request

class MessageForm(FlaskForm):
    message=StringField('Write your message',validators=[DataRequired()])
    submit=SubmitField('Send')

class CreateGroup(FlaskForm):
    group_name=StringField('Group Name',validators=[DataRequired()])
    group_description=StringField('Description')
    group_members=StringField('Username of Members separated by commas ')
    submit=SubmitField('Create Group')

class AddMembers(FlaskForm):
    members=StringField('Members to add separated by commas',validators=[DataRequired()])
    submit=SubmitField('Add members')

class ChangeGroupDescription(FlaskForm):
    description=StringField('New group description',validators=[DataRequired()])
    submit=SubmitField('Change Group Description')

class SearchForm(FlaskForm):
    q=StringField('Search',validators=[DataRequired()])

    def __init__(self,*args,**kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata']=request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled']=False
        super(SearchForm,self).__init__(*args,**kwargs)

slackpro/dockercontents/celery/app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import UserTable
from flask import request

class MessageForm(FlaskForm):
    message=StringField('Write your message',validators=[DataRequired()])
    submit=SubmitField('Send')

class CreateGroup(FlaskForm):
    group_name=StringField('Group Name',validators=[DataRequired()])
    group_description=StringField('Description')
    group_members=StringField('Username of Members separated by commas ')
    submit=SubmitField('Create Group')

class AddMembers(FlaskForm):
    members=StringField('Members to add separated by commas',validators=[DataRequired()])
    submit=SubmitField('Add members')

class ChangeGroupDescription(FlaskForm):
    description=StringField('New group description',validators=[DataRequired()])
    submit=SubmitField('Change Group Description')

class SearchForm(FlaskForm):
    q=StringField('Search',validators=[DataRequired()])

    def __init__(self,*args,**kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata']=request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled']=False
        super(SearchForm,self).__init__(*args,**kwargs)

slackpro/app/dashboard/__init__.py
from flask import Blueprint

bp=Blueprint('dashboard',__name__)

from app.dashboard import routes

slackpro/app/dashboard/routes.py
from flask import render_template,url_for,flash,request,redirect
from flask_login import current_user
from app import db
from app.dashboard import bp
from app.models import UserTable,GroupTable,GroupMembers,Message
from app.dashboard.forms import MessageForm, CreateGroup, AddMembers, ChangeGroupDescription
from flask_socketio import send,emit
from app.services import is_authenticated, get_list_of_groups, get_current_user,create_new_group, get_group, create_message, get_group_single, get_group_members_names, get_group_members, leave_group, add_group_members, change_group_description, delete_group, remove_group_member

@bp.route('/dashboard',methods=['GET','POST'])
def dashboard():
    if is_authenticated():
        groups,username=get_list_of_groups()
        return render_template('dashboard/dashboard.html',groups=groups,username=username)
    else:
        flash('Sorry, you are not logged in. Please login to continue.')
        return redirect(url_for('auth.login'))

@bp.route('/group/<groupid>',methods=['GET','POST'])
def group(groupid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if not(GroupMembers.query.filter_by(member_id=current_user.id).filter_by(group_id=groupid).all()):
        return render_template('errors/404.html'), 404
    user=get_current_user()
    group=get_group(groupid)
    if not(group):
        return render_template('errors/404.html'), 404
    page = request.args.get('page', 1, type=int)
    group=GroupTable.query.filter_by(id=groupid).first()
    if(GroupMembers.query.filter_by(group_id=group.id,member_id=user.id).order_by(Message.message_time.desc())):
        messages=Message.query.filter_by(group_id=group.id).order_by(Message.message_time.desc()).paginate(page,3,False)
        form=MessageForm()
        if form.validate_on_submit():
            create_message(form,groupid,user=user)
            return redirect(url_for('dashboard.group',groupid=groupid))
        next_url = url_for('dashboard.group', page=messages.next_num,groupid=groupid) \
        if messages.has_next else None
        prev_url = url_for('dashboard.group', page=messages.prev_num,groupid=groupid) \
        if messages.has_prev else None
        return render_template('dashboard/messages.html',group=group.id,username=user.username,title=group.groupname,messages=messages.items,form=MessageForm(),groupname=group.groupname,groupdescription=group.group_description,groupid=groupid,next_url=next_url,prev_url=prev_url)
    else:
        flash('Sorry, this group is not found')
        return redirect(url_for('auth.login'))

@bp.route('/creategroup',methods=['GET','POST'])
def creategroup():
    if not(current_user.is_authenticated):
        flash('Sorry, you are not logged in. Please login to continue.')
        return redirect(url_for('auth.login'))
    form=CreateGroup()
    if form.validate_on_submit():
        create_group_bool=create_new_group(form)
        if(create_group_bool):
            flash('Group created successful')
            return redirect(url_for('dashboard.dashboard'))
    return render_template('dashboard/creategroup.html',form=form)

                
@bp.route('/group/<group_id>/groupinfo',methods=['POST','GET'])
def groupinfo(group_id):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if not(GroupMembers.query.filter_by(member_id=current_user.id).filter_by(group_id=group_id).all()):
        return render_template('errors/404.html'), 404
    user=get_current_user()
    group=get_group_single(group_id)
    members=get_group_members(group_id)
    members_names=get_group_members_names(members)
    admin=UserTable.query.filter_by(id=group.admin_id).first()
    form=AddMembers()
    description_form=ChangeGroupDescription()
    if description_form.validate_on_submit():
        change_group_description(description_form,group_id)
        redirect(url_for('dashboard.groupinfo',group_id=group_id))
    if form.validate_on_submit():
        add_group_members(form,group_id)
        return redirect(url_for('dashboard.groupinfo',group_id=group_id))
    if(admin.id!=user.id):
        return render_template('dashboard/showmembers.html',currentid=current_user.id,groupid=group_id,members=members_names,group=group.groupname,description=group.group_description,admin=admin.username,is_admin=False,form=form,changedesc=description_form)
    else:
        return render_template('dashboard/showmembers.html',currentid=current_user.id,groupid=group_id,members=members_names,group=group.groupname,description=group.group_description,admin='You are the admin',is_admin=True,form=form,changedesc=description_form)


@bp.route('/leavegroup/<groupid>',methods=['POST','GET'])
def leavegroup(groupid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if(GroupTable.query.filter_by(id=groupid).first().admin_id==current_user.id):
        flash("You can't leave group in which you are the admin. You can delete the group itself.")
        return redirect(url_for('dashboard.dashboard'))
    groupname=leave_group(groupid)
    flash('You left the group "'+groupname+'"')
    return redirect(url_for('dashboard.dashboard'))

@bp.route('/deletegroup/<groupid>',methods=['POST','GET'])
def deletegroup(groupid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if(GroupTable.query.filter_by(id=groupid).first().admin_id !=current_user.id):
        flash('Unauthorised action')
        return redirect(url_for('dashboard.dashboard'))
    groupname=delete_group(groupid)
    flash('You deleted the group "'+groupname+'"')
    return redirect(url_for('dashboard.dashboard'))

@bp.route('/removemember/<groupid>/<memberid>',methods=['POST','GET'])
def removemember(groupid,memberid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if(GroupTable.query.filter_by(id=groupid).first().admin_id !=current_user.id):
        flash('Unauthorised action')
        return redirect(url_for('dashboard.dashboard'))
    groupmembername=remove_group_member(memberid,groupid)
    flash('You removed "'+groupmembername+'" from the group')
    return redirect(url_for('dashboard.groupinfo',group_id=groupid))

@bp.route('/user/<username>',methods=['POST','GET'])
def user(username):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    user=UserTable.query.filter_by(username=username).first()
    if not(user):
        flash('Sorry user is not found')
        return redirect(url_for('dashboard.dashboard'))
    return render_template('dashboard/user.html',user=user)

slackpro/dockercontents/celery/app/dashboard/__init__.py
from flask import Blueprint

bp=Blueprint('dashboard',__name__)

from app.dashboard import routes

slackpro/dockercontents/celery/app/dashboard/routes.py
from flask import render_template,url_for,flash,request,redirect
from flask_login import current_user
from app import db
from app.dashboard import bp
from app.models import UserTable,GroupTable,GroupMembers,Message
from app.dashboard.forms import MessageForm, CreateGroup, AddMembers, ChangeGroupDescription
from flask_socketio import send,emit
from app.services import is_authenticated, get_list_of_groups, get_current_user,create_new_group, get_group, create_message, get_group_single, get_group_members_names, get_group_members, leave_group, add_group_members, change_group_description, delete_group, remove_group_member

@bp.route('/dashboard',methods=['GET','POST'])
def dashboard():
    if is_authenticated():
        groups,username=get_list_of_groups()
        return render_template('dashboard/dashboard.html',groups=groups,username=username)
    else:
        flash('Sorry, you are not logged in. Please login to continue.')
        return redirect(url_for('auth.login'))

@bp.route('/group/<groupid>',methods=['GET','POST'])
def group(groupid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if not(GroupMembers.query.filter_by(member_id=current_user.id).filter_by(group_id=groupid).all()):
        return render_template('errors/404.html'), 404
    user=get_current_user()
    group=get_group(groupid)
    if not(group):
        return render_template('errors/404.html'), 404
    page = request.args.get('page', 1, type=int)
    group=GroupTable.query.filter_by(id=groupid).first()
    if(GroupMembers.query.filter_by(group_id=group.id,member_id=user.id).order_by(Message.message_time.desc())):
        messages=Message.query.filter_by(group_id=group.id).order_by(Message.message_time.desc()).paginate(page,3,False)
        form=MessageForm()
        if form.validate_on_submit():
            create_message(form,groupid,user=user)
            return redirect(url_for('dashboard.group',groupid=groupid))
        next_url = url_for('dashboard.group', page=messages.next_num,groupid=groupid) \
        if messages.has_next else None
        prev_url = url_for('dashboard.group', page=messages.prev_num,groupid=groupid) \
        if messages.has_prev else None
        return render_template('dashboard/messages.html',group=group.id,username=user.username,title=group.groupname,messages=messages.items,form=MessageForm(),groupname=group.groupname,groupdescription=group.group_description,groupid=groupid,next_url=next_url,prev_url=prev_url)
    else:
        flash('Sorry, this group is not found')
        return redirect(url_for('auth.login'))

@bp.route('/creategroup',methods=['GET','POST'])
def creategroup():
    if not(current_user.is_authenticated):
        flash('Sorry, you are not logged in. Please login to continue.')
        return redirect(url_for('auth.login'))
    form=CreateGroup()
    if form.validate_on_submit():
        create_group_bool=create_new_group(form)
        if(create_group_bool):
            flash('Group created successful')
            return redirect(url_for('dashboard.dashboard'))
    return render_template('dashboard/creategroup.html',form=form)

                
@bp.route('/group/<group_id>/groupinfo',methods=['POST','GET'])
def groupinfo(group_id):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if not(GroupMembers.query.filter_by(member_id=current_user.id).filter_by(group_id=group_id).all()):
        return render_template('errors/404.html'), 404
    user=get_current_user()
    group=get_group_single(group_id)
    members=get_group_members(group_id)
    members_names=get_group_members_names(members)
    admin=UserTable.query.filter_by(id=group.admin_id).first()
    form=AddMembers()
    description_form=ChangeGroupDescription()
    if description_form.validate_on_submit():
        change_group_description(description_form,group_id)
        redirect(url_for('dashboard.groupinfo',group_id=group_id))
    if form.validate_on_submit():
        add_group_members(form,group_id)
        return redirect(url_for('dashboard.groupinfo',group_id=group_id))
    if(admin.id!=user.id):
        return render_template('dashboard/showmembers.html',currentid=current_user.id,groupid=group_id,members=members_names,group=group.groupname,description=group.group_description,admin=admin.username,is_admin=False,form=form,changedesc=description_form)
    else:
        return render_template('dashboard/showmembers.html',currentid=current_user.id,groupid=group_id,members=members_names,group=group.groupname,description=group.group_description,admin='You are the admin',is_admin=True,form=form,changedesc=description_form)


@bp.route('/leavegroup/<groupid>',methods=['POST','GET'])
def leavegroup(groupid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if(GroupTable.query.filter_by(id=groupid).first().admin_id==current_user.id):
        flash("You can't leave group in which you are the admin. You can delete the group itself.")
        return redirect(url_for('dashboard.dashboard'))
    groupname=leave_group(groupid)
    flash('You left the group "'+groupname+'"')
    return redirect(url_for('dashboard.dashboard'))

@bp.route('/deletegroup/<groupid>',methods=['POST','GET'])
def deletegroup(groupid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if(GroupTable.query.filter_by(id=groupid).first().admin_id !=current_user.id):
        flash('Unauthorised action')
        return redirect(url_for('dashboard.dashboard'))
    groupname=delete_group(groupid)
    flash('You deleted the group "'+groupname+'"')
    return redirect(url_for('dashboard.dashboard'))

@bp.route('/removemember/<groupid>/<memberid>',methods=['POST','GET'])
def removemember(groupid,memberid):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    if(GroupTable.query.filter_by(id=groupid).first().admin_id !=current_user.id):
        flash('Unauthorised action')
        return redirect(url_for('dashboard.dashboard'))
    groupmembername=remove_group_member(memberid,groupid)
    flash('You removed "'+groupmembername+'" from the group')
    return redirect(url_for('dashboard.groupinfo',group_id=groupid))

@bp.route('/user/<username>',methods=['POST','GET'])
def user(username):
    if not(is_authenticated()):
        flash('Sorry, you are not logged in. Please login to continue')
        return redirect(url_for('auth.login'))
    user=UserTable.query.filter_by(username=username).first()
    if not(user):
        flash('Sorry user is not found')
        return redirect(url_for('dashboard.dashboard'))
    return render_template('dashboard/user.html',user=user)

slackpro/dockercontents/slackpro/app/dashboard/__init__.py
from flask import Blueprint

bp=Blueprint('dashboard',__name__)

from app.dashboard import routes

slackpro/dockercontents/slackpro/slackpro/app/dashboard/__init__.py
from flask import Blueprint

bp=Blueprint('dashboard',__name__)

from app.dashboard import routes

slackpro/dockercontents/slackpro/slackpro/app/templates/dashboard/creategroup.html
{% extends 'base.html' %}

{% block content %}
<form action='' method='post' novalidate>
    {{ form.hidden_tag() }}
    {{ form.group_name.label(style='font-size:2rem; color:green') }}<br>
    {{ form.group_name }}<br><br>
    {% for error in form.group_name.errors %}
    <span style='color:red'>[{{ error }}]</span><br>
    {% endfor %}<br>
    {{ form.group_description.label(style='font-size:2rem;color:green') }}<br>
    {{ form.group_description(style='width:40%') }}<br><br>
    {% for error in form.group_description.errors %}
    <span style='color:red'>[{{ error }}]</span><br>
    {% endfor %}<br>
    {{ form.group_members.label(style='font-size:2rem;color:green;') }}<br>
    {{ form.group_members }}<br><br>
    {% for error in form.group_members.errors %}
    <span style='color:red'>[{{ error }}]</span><br>
    {% endfor %}<br>
    {{ form.submit(class='btn green') }}
</form>
{% endblock %}

slackpro/dockercontents/slackpro/slackpro/app/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{%  block content %}
<div>
    <h4 style='color:green'>
        Hi, {{ username }}
        <img src="https://avatars.dicebear.com/v2/gridy/{{ username }}.svg" class='avatar-image'>
    </h4>
    <button class='btn green' onclick="window.location.href = '/creategroup';">Create a new
        group</button>
    <br>
    {% if groups %}
    <h4 style='color:green'>Groups in which you are member:</h4>
    <div class="collection">
        {% for group in groups %}
        <a href="/group/{{ group[1] }}" class="collection-item" style='color:black;'><img
                src="https://avatars.dicebear.com/v2/jdenticon/{{ group[0] }}.svg" class='avatar-image'>
            <h6><b>{{ group[0] }}</b></h6>{{ group[2] }}
        </a>
        {% endfor %}
    </div>
    {% else %}
    <h4 style='color:green'>You are not in any group create one</h4>
    {% endif %}
</div>
{% endblock %}

slackpro/dockercontents/slackpro/slackpro/app/templates/dashboard/messages.html
{% extends 'base.html' %}

{% block content %}
<script type='text/javascript' src='{{ url_for("static",filename="message.js") }}'></script>
<span style='display:none' id='groupidnumber'>{{ groupid }}</span>
<span style='display:none' id='username'>{{ username }}</span>
<div>
    <a href='{{ url_for("dashboard.groupinfo",group_id=groupid) }}'><button class='btn green'> Group info </button></a>
    <h3>{{ groupname }}</h3>
    <h4>{{ groupdescription }}</h4>
    <form action='' method='post' novalidate id='messageinputform'>
        {{ form.hidden_tag() }}
        {{ form.message(placeholder='Write Something...',id='messageinputbox') }}
        {% for error in form.message.errors %}
        <br><span class='text-danger'>[{{ error }}]</span><br>
        {% endfor %}
        {{ form.submit(class='btn green') }}
    </form>
    <ul class="collapsible" id='messagecontainer'>
        {% for message in messages %}
        <li>
            <div class="collapsible-header">
                <img src="https://avatars.dicebear.com/v2/gridy/{{ message.user_name }}.svg" class='avatar-image'>
                <span><b>{{ message.user_name }}</b></span><br>
                <span>{{ message.message }}</span>
            </div>
            <div class="collapsible-body">
                <p>Sent : {{ moment(message.message_time).calendar() }} ({{ moment(message.message_time).fromNow() }})
                </p>
            </div>
        </li>
        {% endfor %}
    </ul>

    {% if prev_url %}
    <a href="{{ prev_url }}" class='left'><button class='btn green'>Newer messages</button></a>
    {% endif %}
    {% if next_url %}
    <a href="{{ next_url }}" class='right'><button class='btn green'>Older messages</button></a>
    {% endif %}
</div>

{% endblock %}

slackpro/dockercontents/slackpro/slackpro/app/templates/dashboard/showmembers.html
{% extends 'base.html' %}

{% block content  %}
<script src="http://danml.com/js/download.js"></script>
<script>
    window.onload = function () {
        document.getElementById('changedesc').value = ''
        if (document.getElementById('members')) {
            document.getElementById('members').value = ''
        }
    };
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    async function polling(download_url) {
        let newpromise = await fetch(download_url, { method: 'GET' });
        let downloadDone = await newpromise.text();
        if (downloadDone != 'wait') {
            return downloadDone
        }
        return 'fail'
    }
    async function downloader() {
        document.getElementById('loadingscreen').style.display = 'block';
        document.getElementById('downloadbtn').style.display = 'none';
        var url = 'http://' + window.location.host + '{{ url_for("main.download_content",group_id=groupid,task_id=0)}}';
        let promise = await fetch(url, {
            method: 'GET'
        });
        let responseValue = await promise.text();
        var download_url = 'http://' + window.location.host + '/download/' + responseValue;
        for (let i = 0; i < 20; i++) {
            await sleep(3000);
            var result = await polling(download_url);
            console.log(result);
            if (result != 'fail') {
                document.getElementById('loadingscreen').style.display = 'none';
                document.getElementById('downloadbtn').style.display = 'inline';
                download('http://' + window.location.host + '/download_file/' + result);
                break;
            }
        }
    }
</script>
<div>
    <h4 style='color:green'>Group Name<br>
        <h5> {{ group }} </h5>
    </h4>
    <h4 style='color:green'>Group Description<br>
        <h5> {{ description }} </h5>
    </h4>
    <h4 style='color:green'>Change Group Description</h4>
    <form action='' method='post' novalidate id='addmembersform'>
        {{ form.hidden_tag() }}
        <h5>{{ changedesc.description(id='changedesc') }}</h5>
        {{ changedesc.submit(class='btn green') }}
    </form>

    <h4 style='color:green'>Group Admin<br>
        <h5> {{ admin }} </h5>
    </h4>
    <h4 style='color:green'>Participants</h4>
    {% for member in members %}
    <img src="https://avatars.dicebear.com/v2/gridy/{{ member[0] }}.svg" class='avatar-image'>
    <h5>{{ member[0] }}</h5>
    <h6>{{ member[1].email }}</h6>
    {% if is_admin %}
    {% if currentid != member[1].id %}
    <a href='{{ url_for("dashboard.removemember",groupid=groupid,memberid=member[1].id) }}'><button
            class=' btn green'>Remove member</button></a><br>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% if is_admin %}
    <form action='' method='post' novalidate id='addmembersform'>
        {{ form.hidden_tag() }}
        <h4 style='color:green'>Members to add separated by commas</h4><br>
        {{ form.members }}<br>
        {{ form.submit(class='btn green') }}
    </form>
    <a href='{{ url_for("dashboard.deletegroup",groupid=groupid) }}'><button class=' btn green'>Delete
            Group</button></a>
    {% else %}
    <a href='{{ url_for("dashboard.leavegroup",groupid=groupid) }}'><button class=' btn green'>Leave
            group</button></a>
    {% endif %}
    {% if is_admin %}
    <br>
    <br>
    <a>
        <button class='btn green' onclick="downloader()" id='downloadbtn' style='margin-bottom:50px'>Download
            Chat</button>
    </a>
    <img id='loadingscreen' src="{{ url_for('static',filename='beans.gif') }}" style='display:none;width:100px;'>
    {% endif %}
    <br>
</div> {% endblock %}

slackpro/dockercontents/slackpro/slackpro/app/templates/dashboard/user.html
{% extends 'base.html' %}

{% block content %}
<div>
    <img src="https://avatars.dicebear.com/v2/gridy/{{ user.username }}.svg" class='avatar-image'>
    <h4 style='color:green'>Username</h4>
    <h5>{{ user.username }}</h5>
    <h4 style='color:green'>Email</h4>
    <h5>{{ user.email }}</h5>
</div>
{% endblock  %}